//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class platos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> codigo_chef { get; set; }
    }
}
